### ISSUE TITLE
Sync issue: "preprint is not a valid itemType"

### ISSUE THREAD

**Issue by aitianshi** [victoradrianjimenez/dockerized-zotero#1]
Same issue as another repo "zotprime": https://github.com/uniuuu/zotprime/issues/14

### How to reproduce

- Follow the README instructions (https://github.com/victoradrianjimenez/dockerized-zotero)
- Create an user
- Create a group and add the user created to it
- In the client, log in with the new user
- Click on "Add file" and choose a random document from https://arxiv.org/
- Wait for Sync

### Issue

Show the issue from https://github.com/uniuuu/zotprime/issues/14

**Comment by aitianshi** [comment]
Hi @victoradrianjimenez , I hqve found a way to fix this issue by making a script which generate all database items according to the database schema in zoteroTypeSchemaData.js. Do you want me to make a PR to test it ?

**Comment by victoradrianjimenez** [comment]
Thank you @aitianshi for notifying me about this problem. The database initialization script provided by zotero does not include several data types as "preprint". To fix this problem, it is necessary to call the schema-update.sh script also provided by zotero right after the database creation. I have already made the corresponding commit. Please call this command if you have a database already created: `sudo docker exec -it zotero-dataserver /bin/bash -c "cd /var/www/zotero/admin/ && ./schema_update"`

**Comment by victoradrianjimenez** [comment]
Thank you @aitianshi for notifying me about this problem. The database initialization script provided by zotero does not include several data types as "preprint". To fix this problem, it is necessary to call the schema-update.sh script also provided by zotero right after the database creation. I have already made the corresponding commit. Please call this command if you have a database already created: `sudo docker exec -it zotero-dataserver /bin/bash -c "cd /var/www/zotero/admin/ && ./schema_update"`
